name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for full Git context

      - name: Verify checkout and list files
        run: |
          echo "Current directory: $(pwd)"
          echo "Verifying repository checkout..."
          ls -la . || echo "No files in current directory"
          find . -type f || echo "No files found recursively"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to gh-pages branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Remove existing gh-pages branch if it exists
          git checkout main
          git branch -D gh-pages || echo "gh-pages branch does not exist, proceeding..."
          # Create a new gh-pages branch
          git checkout -b gh-pages
          # Force add all files to ensure they are staged
          git add -A
          # Commit changes, allowing an empty commit if no changes are detected
          git commit -m "Deploy to GitHub Pages" --allow-empty
          # Push to gh-pages branch
          git push origin gh-pages --force
