name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Required for deploying to GitHub Pages
      id-token: write   # Required for actions/deploy-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for full Git context

      - name: Set up Node.js (optional, for future use)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Determine working directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository path: $(pwd)/frp-tool-web"
          echo "Listing repository directory:"
          ls -la $(pwd)/frp-tool-web
          echo "Listing files to upload:"
          find $(pwd)/frp-tool-web -type f

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            $(pwd)/frp-tool-web/index.html
            $(pwd)/frp-tool-web/styles.css
            $(pwd)/frp-tool-web/script.js
            $(pwd)/frp-tool-web/logo.png
            $(pwd)/frp-tool-web/telegram.png
            $(pwd)/frp-tool-web/Honor_Images/
            $(pwd)/frp-tool-web/.nojekyll
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
