name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Required for deploying to GitHub Pages
      id-token: write   # Required for actions/deploy-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for full Git context

      - name: Set up Node.js (optional, for future use)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Determine working directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing repository directory:"
          ls -la $(pwd)
          echo "Listing files to upload:"
          find $(pwd) -type f

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            ./index.html
            ./styles.css
            ./script.js
            ./logo.png
            ./telegram.png
            ./Honor_Images/
            ./.nojekyll
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
